# -*- coding: utf-8 -*-
"""Exercício Módulo 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCElYrEyf2NbVoCmPcNo66qUvXq0T7vF

# Primeiro código, Simples
## Código básico com operações matemáticas apresentadas de forma automática para o usuário
"""

variavel1 = input ("Insira o numero da variavel 1: ")

variavel2 = input ("Insira o numero da variavel 2: ")

variavel1_convert = int(variavel1)

variavel2_convert = int(variavel2)

soma = int(variavel1) + int(variavel2)


print ("A soma das duas variáveis é:" , soma)
print ("A subtração das duas variáveis é:" , variavel1_convert - variavel2_convert)
print ("A multiplicação das duas variáveis é:" , variavel1_convert * variavel2_convert)
print ("A divisão das duas variáveis é:" , variavel1_convert / variavel2_convert)
print ("O resto da divisão das duas variáveis é:" , variavel1_convert % variavel2_convert)
print ("A exponenciação das duas variáveis é:" , variavel1_convert ** variavel2_convert)

"""# Segundo código, mais interativo
## Permite o usuário interagir com o menu, escolher qual operação realizar
"""

variavel1 = input("Insira o numero da variavel 1: ")
variavel2 = input("Insira o numero da variavel 2: ")

variavel1_convert = int(variavel1)
variavel2_convert = int(variavel2)

print("Escolha a operação:")
print("1. Soma")
print("2. Subtração")
print("3. Multiplicação")
print("4. Divisão")
print("5. Resto da divisão")
print("6. Exponenciação")

escolha = input("Digite o número da operação desejada: ")

if escolha == '1':
    print("A soma das duas variáveis é:", variavel1_convert + variavel2_convert)
elif escolha == '2':
    print("A subtração das duas variáveis é:", variavel1_convert - variavel2_convert)
elif escolha == '3':
    print("A multiplicação das duas variáveis é:", variavel1_convert * variavel2_convert)
elif escolha == '4':
    print("A divisão das duas variáveis é:", variavel1_convert / variavel2_convert)
elif escolha == '5':
    print("O resto da divisão das duas variáveis é:", variavel1_convert % variavel2_convert)
elif escolha == '6':
    print("A exponenciação das duas variáveis é:", variavel1_convert ** variavel2_convert)
else:
    print("Opção inválida.")



























